
export const ACCOUNT_CREATE_BEGIN = 'ACCOUNT_CREATE_BEGIN'
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS'
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL'


export const ACCOUNT_LOGIN_BEGIN = 'ACCOUNT_LOGIN_BEGIN'
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS'
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL'

export const ACCOUNT_FORGOT_PASSWORD_BEGIN = 'ACCOUNT_FORGOT_PASSWORD_BEGIN'
export const ACCOUNT_FORGOT_PASSWORD_SUCCESS = 'ACCOUNT_FORGOT_PASSWORD_SUCCESS'
export const ACCOUNT_FORGOT_PASSWORD_FAIL = 'ACCOUNT_FORGOT_PASSWORD_FAIL'

export const ACCOUNT_INIT_PASSWORD_BEGIN = 'ACCOUNT_INIT_PASSWORD_BEGIN'
export const ACCOUNT_INIT_PASSWORD_SUCCESS = 'ACCOUNT_INIT_PASSWORD_SUCCESS'
export const ACCOUNT_INIT_PASSWORD_FAIL = 'ACCOUNT_INIT_PASSWORD_FAIL'

export const REDIRECT = 'REDIRECT'