<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.viosmash</groupId>
  <artifactId>social-network</artifactId>
  <packaging>pom</packaging>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.4.0</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <modules>
    <module>framework</module>
    <module>gateway</module>
    <module>config-server</module>
    <module>discovery-services</module>
    <module>dependencies</module>
    <module>framework/mq</module>
    <module>framework/security</module>
    <module>framework/redis</module>
    <module>services/authen-service</module>
    <module>services/profile-service</module>
    <module>services/profile-service/profile-api</module>
    <module>services/profile-service/profile</module>
    <module>services/friendship-service</module>
    <module>services/notification-service</module>
    <module>services/post-service</module>
    <module>services/group-service</module>
    <module>services/upload-service</module>
    <module>services/chat-service</module>
      <module>services/newfeed-service</module>
  </modules>
  <properties>
    <java.version>17</java.version>
    <mapstruct.version>1.3.1.Final</mapstruct.version>
    <lombok.version>1.18.12</lombok.version>
    <spring-cloud.version>2024.0.0</spring-cloud.version>
  </properties>

  <version>1.0-SNAPSHOT</version>
  <name>social-network Maven Webapp</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>com.viosmash</groupId>
      <artifactId>dependencies</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${mapstruct.version}</version>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <finalName>social-network</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
