spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_reactive?createIfNotExists=true
    username: root
    password: root
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
