spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**