server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**

        - id: friendship-service
          uri: lb://FRIENDSHIP-SERVICE
          predicates:
            - Path=/api/friendship/**
      discovery:
        locator:
          enabled: true