server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**

        - id: friendship-service
          uri: lb://FRIENDSHIP-SERVICE
          predicates:
            - Path=/api/friendship/**

        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/api/groups/**
            - Path=/api/members/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chats/**

        - id: chat-sockjs-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/ws/info/**
        - id: chat-service-route
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/chat/ws/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
              - Path=/api/posts/**

        - id: interaction-service
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/api/interactions/**
      discovery:
        locator:
          enabled: true