viosmash:
  websocket:
    endpoint: /chat/ws
    appPrefix: /app
    destinationPrefix: /topic
  topic:
    newConversation: /topic/chat/user/%d
    notification: /topic/chat/soundNotification/user/%d
    chat: /topic/chat/conversation/%s

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_chat_service?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084