server:
  port: 8083

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: nguyenquangphu
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10