server:
  port: 8081

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_profile_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.cj.Driver