


export const ACCOUNT_LOGIN_BEGIN = 'ACCOUNT_LOGIN_BEGIN'
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS'
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL'

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'



export const ACCOUNT_INIT_PASSWORD_BEGIN = 'ACCOUNT_INIT_PASSWORD_BEGIN'
export const ACCOUNT_INIT_PASSWORD_SUCCESS = 'ACCOUNT_INIT_PASSWORD_SUCCESS'
export const ACCOUNT_INIT_PASSWORD_FAIL = 'ACCOUNT_INIT_PASSWORD_FAIL'

export const REDIRECT = 'REDIRECT'