export const FETCH_LIST_MESSAGE_BEGIN = "FETCH_LIST_MESSAGE_BEGIN"
export const FETCH_LIST_MESSAGE_SUCCESS = "FETCH_LIST_MESSAGE_SUCCESS"
export const FETCH_LIST_MESSAGE_FAILED = "FETCH_LIST_MESSAGE_FAILED"

export const FETCH_LIST_CONVERSATION_SUCCESS = "FETCH_LIST_CONVERSATION_SUCCESS"
export const FETCH_LIST_CONVERSATION_FAILED = "FETCH_LIST_CONVERSATION_FAILED"
export const UPDATE_NEWEST_MESSAGE = "UPDATE_NEWEST_MESSAGE"

export const CREATE_CONVERSATION_BEGIN = "CREATE_CONVERSATION_BEGIN"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_FAILED = "CREATE_CONVERSATION_FAILED"