export const FETCH_LIST_MESSAGE_BEGIN = "FETCH_LIST_MESSAGE_BEGIN"
export const FETCH_LIST_MESSAGE_SUCCESS = "FETCH_LIST_MESSAGE_SUCCESS"
export const FETCH_LIST_MESSAGE_FAILED = "FETCH_LIST_MESSAGE_FAILED"