export const ACCEPT_FRIEND_REQUEST_BEGIN = "ACCEPT_FRIEND_REQUEST_BEGIN"
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS"
export const ACCEPT_FRIEND_REQUEST_FAILED = "ACCEPT_FRIEND_REQUEST_FAILED"


export const DENY_FRIEND_REQUEST_BEGIN = "DENY_FRIEND_REQUEST_BEGIN"
export const DENY_FRIEND_REQUEST_SUCCESS = "DENY_FRIEND_REQUEST_SUCCESS"
export const DENY_FRIEND_REQUEST_FAILED = "DENY_FRIEND_REQUEST_FAILED"

/**
 * 
 */
export const CANCEL_FRIEND_REQUEST_BEGIN = "CANCEL_FRIEND_REQUEST_BEGIN"
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS"
export const CANCEL_FRIEND_REQUEST_FAILED = "CANCEL_FRIEND_REQUEST_FAILED"

export const CREATE_FRIEND_REQUEST_BEGIN = "CREATE_FRIEND_REQUEST_BEGIN"
export const CREATE_FRIEND_REQUEST_SUCCESS = "CREATE_FRIEND_REQUEST_SUCCESS"
export const CREATE_FRIEND_REQUEST_FAILED = "CREATE_FRIEND_REQUEST_FAILED"

export const FETCH_FRIEND_REQUEST_BY_SENDER_BEGIN = "FETCH_FRIEND_REQUEST_BY_SENDER_BEGIN"
export const FETCH_FRIEND_REQUEST_BY_SENDER_SUCCESS = "FETCH_FRIEND_REQUEST_BY_SENDER_SUCCESS"
export const FETCH_FRIEND_REQUEST_BY_SENDER_FAILED = "FETCH_FRIEND_REQUEST_BY_SENDER_FAILED"

export const FETCH_FRIEND_REQUEST_BY_RECEIVER_BEGIN = "FETCH_FRIEND_REQUEST_BY_RECEIVER_BEGIN"
export const FETCH_FRIEND_REQUEST_BY_RECEIVER_SUCCESS = "FETCH_FRIEND_REQUEST_BY_RECEIVER_SUCCESS"
export const FETCH_FRIEND_REQUEST_BY_RECEIVER_FAILED = "FETCH_FRIEND_REQUEST_BY_RECEIVER_FAILED"

export const FETCH_SUGGESTION_USER_BEGIN = "FETCH_SUGGESTION_USER_BEGIN"
export const FETCH_SUGGESTION_USER_SUCCESS = "FETCH_SUGGESTION_USER_SUCCESS"
export const FETCH_SUGGESTION_USER_FAILED = "FETCH_SUGGESTION_USER_FAILED"


