
export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED"


export const FETCH_PAGE_COMMENT_BY_POST_BEGIN = "FETCH_PAGE_COMMENT_BY_POST_BEGIN"
export const FETCH_PAGE_COMMENT_BY_POST_SUCCESS = "FETCH_PAGE_COMMENT_BY_POST_SUCCESS"
export const FETCH_PAGE_COMMENT_BY_POST_FAILED = "FETCH_PAGE_COMMENT_BY_POST_FAILED"
export const ADD_NEW_COMMENT_TO_PAGE = "ADD_NEW_COMMENT_TO_PAGE"

export const UPDATE_LIKE_BEGIN = "UPDATE_LIKE_BEGIN"
export const UPDATE_LIKE_SUCCESS = "UPDATE_LIKE_SUCCESS"
export const UPDATE_LIKE_FAILED = "UPDATE_LIKE_FAILED"

