export const UPDATE_CHAT_ENABLE_BEGIN = "UPDATE_CHAT_ENABLE_BEGIN"
export const UPDATE_CHAT_ENABLE_SUCCESS = "UPDATE_CHAT_ENABLE_SUCCESS"
export const UPDATE_CHAT_ENABLE_FAILED = "UPDATE_CHAT_ENABLE_FAILED"

export const UPDATE_COMMENT_ENABLE_BEGIN = "UPDATE_COMMENT_ENABLE_BEGIN"
export const UPDATE_COMMENT_ENABLE_SUCCESS = "UPDATE_COMMENT_ENABLE_SUCCESS"
export const UPDATE_COMMENT_ENABLE_FAILED = "UPDATE_COMMENT_ENABLE_FAILED"


export const UPDATE_REACTION_ENABLE_BEGIN = "UPDATE_REACTION_ENABLE_BEGIN"
export const UPDATE_REACTION_ENABLE_SUCCESS = "UPDATE_REACTION_ENABLE_SUCCESS"
export const UPDATE_REACTION_ENABLE_FAILED = "UPDATE_REACTION_ENABLE_FAILED"

export const UPDATE_FRIEND_ENABLE_BEGIN = "UPDATE_FRIEND_ENABLE_BEGIN"
export const UPDATE_FRIEND_ENABLE_SUCCESS = "UPDATE_FRIEND_ENABLE_SUCCESS"
export const UPDATE_FRIEND_ENABLE_FAILED = "UPDATE_FRIEND_ENABLE_FAILED"

export const FETCH_NOTIFY_MESSAGE_BEGIN = "FETCH_NOTIFY_MESSAGE_BEGIN"
export const FETCH_NOTIFY_MESSAGE_SUCCESS = "FETCH_NOTIFY_MESSAGE_SUCCESS"
export const FETCH_NOTIFY_MESSAGE_FAILED = "FETCH_NOTIFY_MESSAGE_FAILED"


export const READ_NOTIFY_MESSAGE_BEGIN = "READ_NOTIFY_MESSAGE_BEGIN"
export const READ_NOTIFY_MESSAGE_SUCCESS = "READ_NOTIFY_MESSAGE_SUCCESS"
export const READ_NOTIFY_MESSAGE_FAILED = "READ_NOTIFY_MESSAGE_FAILED"


export const READ_ALL_NOTIFY_MESSAGE_BEGIN = "READ_ALL_NOTIFY_MESSAGE_BEGIN"
export const READ_ALL_NOTIFY_MESSAGE_SUCCESS = "READ_ALL_NOTIFY_MESSAGE_SUCCESS"
export const READ_ALL_NOTIFY_MESSAGE_FAILED = "READ_ALL_NOTIFY_MESSAGE_FAILED"

export const COUNT_UNREAD_MESSAGE_BEGIN = "COUNT_UNREAD_MESSAGE_BEGIN"
export const COUNT_UNREAD_MESSAGE_SUCCESS = "COUNT_UNREAD_MESSAGE_SUCCESS"
export const COUNT_UNREAD_MESSAGE_FAILED = "COUNT_UNREAD_MESSAGE_FAILED"

export const FETCH_NOTIFY_SETTING_BEGIN = "FETCH_NOTIFY_SETTING_BEGIN"
export const FETCH_NOTIFY_SETTING_SUCCESS = "FETCH_NOTIFY_SETTING_SUCCESS"
export const FETCH_NOTIFY_SETTING_FAILED = "FETCH_NOTIFY_SETTING_FAILED"