export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAILED = "CREATE_POST_FAILED"

export const FETCH_LIST_POST_BY_USER_BEGIN = "FETCH_LIST_POST_BY_USER_BEGIN"
export const FETCH_LIST_POST_BY_USER_SUCCESS = "FETCH_LIST_POST_BY_USER_SUCCESS"
export const FETCH_LIST_POST_BY_USER_FAILED = "FETCH_LIST_POST_BY_USER_FAILED"


export const FETCH_POST_BY_ID_BEGIN = "FETCH_POST_BY_ID_BEGIN"
export const FETCH_POST_BY_ID_SUCCESS = "FETCH_POST_BY_ID_SUCCESS"
export const FETCH_POST_BY_ID_FAILED = "FETCH_POST_BY_ID_FAILED"


