export const UPDATE_INFO_BEGIN = "UPDATE_INFO_BEGIN"
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS"
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL"

export const UPLOAD_COVER_PHOTO_BEGIN = ""
export const UPLOAD_COVER_PHOTO_SUCCESS = ""
export const UPLOAD_COVER_PHOTO_FAIL = ""

export const UPLOAD_PERSONAL_IMAGE_BEGIN = ""
export const UPLOAD_PERSONAL_IMAGE_SUCCESS = ""
export const UPLOAD_PERSONAL_IMAGE_FAIL = ""

export const UPDATE_EDUCATION_BEGIN = ""
export const UPDATE_EDUCATION_SUCCESS = ""
export const UPDATE_EDUCATION_FAIL = ""


export const UPDATE_ADDRESS_BEGIN = ""
export const UPDATE_ADDRESS_SUCCESS = ""
export const UPDATE_ADDRESS_FAIL = ""

export const UPDATE_MESSAGE_PRIVACY_BEGIN = ""
export const UPDATE_MESSAGE_PRIVACY_SUCCESS = ""
export const UPDATE_MESSAGE_PRIVACY_FAIL = ""

export const UPDATE_POST_PRIVACY_BEGIN = ""
export const UPDATE_POST_PRIVACY_SUCCESS = ""
export const UPDATE_POST_PRIVACY_FAIL = ""

export const UPDATE_NOTIFCATION_PRIVACY_BEGIN = ""
export const UPDATE_NOTIFCATION_PRIVACY_SUCCESS = ""
export const UPDATE_NOTIFCATION_PRIVACY_FAIL = ""

export const FETCH_COMMON_PROFILE_BEGIN = "FETCH_COMMON_PROFILE_BEGIN"
export const FETCH_COMMON_PROFILE_FAILED = "FETCH_COMMON_PROFILE_FAILED"
export const FETCH_COMMON_PROFILE_SUCCESS = "FETCH_COMMON_PROFILE_SUCCESS"

export const UPDATE_PERSONAL_GALLERY_IMAGES_BEGIN = "UPDATE_PERSONAL_GALLERY_IMAGES_BEGIN"
export const UPDATE_PERSONAL_GALLERY_IMAGES_SUCCESS = "UPDATE_PERSONAL_GALLERY_IMAGES_SUCCESS"
export const UPDATE_PERSONAL_GALLERY_IMAGES_FAILED= "UPDATE_PERSONAL_GALLERY_IMAGES_FAILED"

export const FETCH_BASIC_INFO_USER_BEGIN = ""
export const FETCH_BASIC_INFO_USER_SUCCESS = ""
export const FETCH_BASIC_INFO_USER_FAILED = ""

export const FETCH_INFO_USER_ADDRESS_BEGIN = ""
export const FETCH_INFO_USER_ADDRESS_SUCCESS = ""
export const FETCH_INFO_USER_ADDRESS_FAILED = ""


export const FETCH_INFO_USER_EDUCATION_BEGIN = ""
export const FETCH_INFO_USER_EDUCATION_SUCCESS = ""
export const FETCH_INFO_USER_EDUCATION_FAILED = ""
